### ISSUE TITLE
Kiba-common licence?

### ISSUE THREAD

**Issue by blijblijblij** [thbar/kiba-common#12]
You nicely include some contributing and legal:

> # Contributing & Legal
> 
> (agreement below borrowed from Sidekiq Legal)
>
> By submitting a Pull Request, you disavow any rights or claims to any changes submitted to the Kiba Common project and assign the copyright of those changes to LoGeek SARL.
> 
> If you cannot or do not want to reassign those rights (your employment contract for your employer may not allow this), you should not submit a PR. Open an issue and someone else can do the work.
> 
> This is a legal way of saying "If you submit a PR to us, that code becomes ours". 99.9% of the time that's what you intend anyways; we hope it doesn't scare you away from contributing.

But there is no actual license included. Is this intentional? Or just never came to mind?

I have no particular opinion on the subject, was just curious and was somehow expecting a license to be stated as github makes this trivial.

With kind regards, Rogier

**Comment by thbar** [comment]
Hi Rogier!

The license is declared in the `LICENSE` file available [here](https://github.com/thbar/kiba-common/blob/master/LICENSE), and states:

> Kiba Common is an Open Source project licensed under the terms of
the LGPLv3 license.  Please see <http://www.gnu.org/licenses/lgpl-3.0.html>
for license text.

I'll update the README to point to that file.

**Comment by blijblijblij** [comment]
Thanks for the clarification! 👍

**Comment by thbar** [comment]
You welcome! Thanks for asking!

Envoyé de mon iPhone
