### ISSUE TITLE
Create a first release?

### ISSUE THREAD

**Issue by pmackay** [thbar/kiba-common#2]
Hi @thbar, is there any chance of creating a first release of this gem? I'm encountering some problems loading it when building a commandline tool and am wondering if it is because its loading from the repo.

**Comment by thbar** [comment]
Hi Paul - I can prepare a release, no problem! Will keep you posted.

Envoyé de mon iPhone

**Comment by thbar** [comment]
Hi @pmackay - the `kiba-common` gem has been released as version 0.0.1. Can you try it out and let me know how it goes? Thanks!

**Comment by pmackay** [comment]
Thanks for creating a release, very helpful to be able to have a simpler gem reference in Gemfile. I think I may have been confusing myself partly though as I was trying a `require 'kiba-common'` which doesnt work - I needed to be requiring only the show_me module...

**Comment by thbar** [comment]
> Thanks for creating a release, very helpful to be able to have a simpler gem reference in Gemfile.

You welcome! I'll update the readme shortly.

>  I think I may have been confusing myself partly though as I was trying a require 'kiba-common' which doesnt work - I needed to be requiring only the show_me module...

Ah, that would make sense. I'll make it clearer in the readme, and I could also maybe in the future offer something like `require 'active_support/all'` to load everything by default.

Closing this one, thanks for your request!
