### ISSUE TITLE
Publish a CSV source

### ISSUE THREAD

**Issue by thbar** [thbar/kiba-common#7]
A CSV source is a very common requirement ; yet I have to verify all the various implementations I've made recently to come up with something generic enough.

**Comment by mauriciopasquier** [comment]
I was going to make a pull request with my implementation (it basically allows to pass options).

Although I recenlty found one with [a better implementation](https://github.com/SnackNation/kiba-uncommon/blob/078e2f4c01a551aaba0810fd2d54e5243d5996cd/lib/kiba/uncommon/sources/csv.rb#L13-L17) of `each`, I think it really belongs in this gem.

```ruby
def initialize(input_file, csv_options: { })
  @input_file = input_file
  @opts = default_options.merge csv_options
end

# Sane defaults
def default_options
  {
    headers: true,
    header_converters: :symbol,
    col_sep: ',',
    encoding: 'utf-8'
  }
end
```

**Comment by thbar** [comment]
@mauriciopasquier thanks for the comment!

There are a few extra needs that I need to ensure are covered for various clients I'm working for. I've started consolidating those in a new `csv-source` branch (WIP).

I will update this issue once it's ready. Thanks!

**Comment by thbar** [comment]
@mauriciopasquier could you try out the version published in #15 and let me know if this works for you? (except for the defaults which you'll have to provide). I've postponed more advanced needs for now, in favour of publishing this most-needed component earlier. Thanks!

**Comment by mauriciopasquier** [comment]
Awesome, thanks! I'll try it and report back

**Comment by mauriciopasquier** [comment]
It works great, thanks!

I still think it is reasonable to include defaults baked in for "sane" csv processing, but I'll favor having an official component released over bikeshedding :)

**Comment by thbar** [comment]
@mauriciopasquier thanks for testing!

>  I'll favor having an official component released over bikeshedding :)

This is greatly appreciated too, thanks!

**Comment by thbar** [comment]
Version 0.0.9 is out with the new CSV source.

**Comment by mauriciopasquier** [comment]
Thanks!
